"""add users table

Revision ID: 11a09897a203
Revises: f1b22144d805
Create Date: 2026-08-30 00:50:22.695359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11a09897a203'
down_revision: Union[str, Sequence[str], None] = 'f1b22144d805'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_index(op.f('ix_browser_artifacts_investigation_id'), 'browser_artifacts', ['investigation_id'], unique=False)
    op.create_index(op.f('ix_browser_sessions_investigation_id'), 'browser_sessions', ['investigation_id'], unique=False)
    op.create_index(op.f('ix_candidate_entities_investigation_id'), 'candidate_entities', ['investigation_id'], unique=False)
    op.add_column('research_tasks', sa.Column('intervention_type', sa.String(length=100), nullable=True))
    op.add_column('research_tasks', sa.Column('intervention_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('research_tasks', 'intervention_reason')
    op.drop_column('research_tasks', 'intervention_type')
    op.drop_index(op.f('ix_candidate_entities_investigation_id'), table_name='candidate_entities')
    op.drop_index(op.f('ix_browser_sessions_investigation_id'), table_name='browser_sessions')
    op.drop_index(op.f('ix_browser_artifacts_investigation_id'), table_name='browser_artifacts')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
